spring.datasource.url=jdbc:h2:mem:recommendation;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.flyway.locations=classpath:db/migration-local
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
platform.seed.config-path=${SEED_CONFIG_PATH:../../projects/taean-flower/taean-flower-project-config.json}
